### PR TITLE
Changing clap to structopt

### PR DESCRIPTION
**Pull request by yancouto**
Hello! I was looking around LOVE forum and found this :). I caught my attention because I know distributing is hard for LOVE and I'm also trying to learn Rust right now.

This PR simply changes the command line lib from clap to structopt (which still uses clap under the hood, but has some nice type magic that makes it easier to read and write code). Behaviour shouldn't change, except for one thing: I added `boon love list` instead of simply using `boon love`, since it was easier and clearer (I only found about this subcommand when reading the code :P).

I did this mostly to experiment a bit with Rust, seeing how it is to do some mild refactoring. Compiler really helps you out, though it's hard to get to some "intermediate working" version of the code when you start changing stuff. Feel free to reject this, I was just experimenting with some real code.

Now, about LOVE: I did [some post](https://love2d.org/forums/viewtopic.php?f=5&t=86059&p=224382#p224382) about distributing games (based on my experience for a game I published). I had some problems setting up love-release, which is one of the reason I liked this project.

Some random thought: For linux builds, distributing as AppImage seems ideal. I wrote about how I did it for my game in the post (hacking a bunch of stuff), but LOVE >=11 is also distributed as an AppImage, so it should be really easy to just extract it, move some files around and repackage it to get a working Linux build! Only problem is AppImage tool only works on Linux! I would love to submit a PR for this, but I'm no longer developing games using love (and my last one didn't even use LOVE 11).

### CODE REVIEW

**Comment by camchenry** [comment]
Hi, thank you for the pull request. I have not read over it in depth, I will try to read over it when I have some time. Glancing over it, the one thing that stood out to me is the primitive enum conversions. I don't think I understand the reasoning behind it. Otherwise, I think it looks like pretty similar to the original code.

Admittedly, this was also a project that helped me learn Rust so I can't say that if I wrote this project today I would make the same decisions that I did when I wrote this. I would probably have written more tests earlier on, although I have recently started to add more end-to-end build tests that actually verify the build artifact. Some tests make the refactoring process even smoother in my experience. Like you I also haven't written anything with LOVE for a few years now, but I enjoy writing tools for it in Rust anyway.

One of the reasons for writing this tool in Rust (beyond the fact that I just wanted to learn it) is that I think a build tool like this can and should be usable across different platforms. Rust has great support for Windows, and I think many Linux-focused languages and tools miss out on that. Likewise, there are plenty of Windows-only languages and tools. I understand game developers use platforms of all kinds, and I want a tool that "just works" on all of them. (And it should be fast!) There's no good reason a build tool can't work cross-platform. 

I have thought about AppImages a bit, and I only recently learned that LOVE now has AppImage distributions. I don't think I would want to officially support Linux using that method though, because as you say, the AppImage tool only works on Linux and that doesn't align with my goal of keeping boon cross-platform. Ultimately, an AppImage is just some files arranged in a prescribed format, so there's no reason you can't construct that across different platforms. I think it would be great to build a pure Rust library that is indepedent of boon which can build AppImages in memory, and then allow library users to choose how to output it. I'd be interested to hear thoughts that you have.

**Comment by yancouto** [comment]
Thanks for the reply.

**About the primitive enum stuff**: I was trying to make enums that can be converted to and from strings as simple as possible. I found out that `clap` has this nice macro called `arg_enum` which does that for you, so I used that for `enum Target` and it was really simple.

For the `LoveVersion` enum though, it wasn't simple since we can't have enum names with dots and such, so couldn't use `arg_enum`. The `Display` and `FromStr` traits each currently had manual implementations for `LoveVersion` (meaning if you added a version you would need to add it to multiple places), so I tried  to reduce this by using primitive enums and such :P. It was more complicated than I hoped. It seems if I had searched a little more I could've found a crate that made that way simpler, like [this](https://crates.io/crates/enum_from_str) or [this](https://crates.io/crates/enum_str).

**About AppImage and Linux**: Yes, ideally it could be built from anywhere. But that is not the case today: there have been discussions (https://github.com/AppImage/AppImageKit/issues/463, https://github.com/AppImage/AppImageKit/issues/322) about making it possible on Mac, seems possible but didn't  happen. And Windows is even further away.

Something that might work and can be done xplat is simply using the prebundled love AppImage and calling it on the `.love`, using a shell script or something. Should work for most linux and should be easy to create in any platform, since the love AppImage is already done.

**Comment by camchenry** [comment]
Just wanted to leave a comment here that I've not forgotten about this PR. Life has brought lots of business and things to do. Unfortunately, that means projects take up less of my time. I still like the changes, but I'd like to go over them.

**Comment by camchenry** [comment]
I apologize for the long delay. I finally merged the branch which adds an extra check for the Windows tests which I wanted to wait for because this is the first major pull request I have received. So, thank you for your contribution. I greatly appreciate it. 

With that said, I looked over the code and I am okay with merging it in its current form. I would like to see if the primitive enum code can be improved, but it is functional for now.

**Pull request merged**
