### PR TITLE
add 11.5 support

### PR DESCRIPTION
**Pull request by gingerbeardman**

### CODE REVIEW

**Comment by camchenry** [comment]
This looks good, but there was an error with the array lengths. I updated this code to used inferred array lengths instead, as that seems slightly more maintainable: https://github.com/gingerbeardman/boon/pull/1.

**Comment by gingerbeardman** [comment]
Thanks! @camchenry merged in my fork

I didn't compile the code (lack of time, put off by other issues saying there were compile problems so simply didn't try) so was flying blind and missed some things. :)

**Comment by camchenry** [comment]
@gingerbeardman looks like CI is broken, which is unfortunate. I'll need to look into fixing that before merging, sorry.

**Comment by camchenry** [comment]
Looks like this is working now, thank you again for the contribution.

**Pull request merged**
